routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\FicConfigController;
use App\Http\Controllers\Admin\StaticPageController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\InitiativeController;
use App\Http\Controllers\IdeaController;
use App\Http\Controllers\SuggestController;
use App\Http\Controllers\CollectiveController;
use App\Http\Controllers\ReactionController;
use App\Http\Controllers\ModerateController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PhotoController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();


Route::get('/', 'HomeController@index')->name('home');


// Admin Routes
Route::namespace('Admin')->prefix('/admin')->group(function () {

	Route::get('/', [AdminController::class, 'index'])->name('adminHome');

	Route::get('/config', [FicConfigController::class, 'edit'])->name('configuration');
	Route::put('/config/header', [FicConfigController::class, 'updateHeader'])->name('configuration.updateHeader');
	Route::put('/config/footer', [FicConfigController::class, 'updateFooter'])->name('configuration.updateFooter');
	Route::put('/config/socialize', [FicConfigController::class, 'updateSocialize'])->name('configuration.updateSocialize');
	Route::post('/config/socialize', [FicConfigController::class, 'addSocialize'])->name('configuration.addSocialize');
	Route::delete('/config/socialize-delete/{ficConfig}', [FicConfigController::class, 'deleteSocialize'])->name('configuration.deleteSocialize');
  Route::get('/collectives', [CollectiveController::class, 'showAdmin'])->name('collectives.admin');
  Route::get('/collectives/ref-collectives', [CollectiveController::class, 'refColl'])->name('collectives.ref-coll');
  Route::get('/collectives/member-collectives', [CollectiveController::class, 'memberColl'])->name('collectives.member-coll');
  Route::get('/collectives/create', [CollectiveController::class, 'createColl'])->name('collectives.create');
  Route::get('/profil', [UserController::class, 'dashboard'])->name('dashboard');
  Route::get('/messages', [ContactController::class, 'index'])->name('all_messages');
  Route::get('/message/{contact}', [ContactController::class, 'showMessage'])->name('show_message');
  Route::get('/initiatives', [InitiativeController::class, 'indexAdmin'])->name('initiatives-admin');
});

Route::resources([
	'/admin/profile' => Admin\UserController::class,
	'/admin/categories' => 'CategoryController',
  '/admin/static-pages' => Admin\StaticPageController::class
]);

Route::post('/user/add-picture', [UserController::class, 'addPicture']);
Route::delete('/user/delete-picture/{user}', [UserController::class, 'deletePicture']);
Route::post('/user/ban', [UserController::class, 'ban']);

// Initiatives Routes
Route::resource('/initiatives', 'InitiativeController');
Route::post('/initiative', [InitiativeController::class, 'show']);
Route::post('/initiative-home', [InitiativeController::class, 'homeInitiative']);
Route::get('/initiative/{category}', [InitiativeController::class, 'initByCat']);
Route::post('/initiative-join', [InitiativeController::class, 'joinInitiative']);
Route::put('/update-initiative', [InitiativeController::class, 'updateInit']);
Route::delete('/delete-initiative/{initiative}', [InitiativeController::class, 'deleteInit']);

// Ideas Routes
Route::resource('/ideas', 'IdeaController');
Route::post('/idea-recent-home', [IdeaController::class, 'homeIdeaRecent']);
Route::post('/idea-popular-home', [IdeaController::class, 'homeIdeaPopular']);
Route::get('/idea/{category}', [IdeaController::class, 'ideaByCat']);

// Suggest Routes
Route::get('/suggest/idea', [SuggestController::class, 'index']);
Route::get('/suggest/initiative', [SuggestController::class, 'index']);
Route::get('/transform/{idea}', [IdeaController::class, 'transformIdea']);

// Save Items Routes
Route::post('/save-initiative', [InitiativeController::class, 'store'] );
Route::post('/save-idea', [IdeaController::class, 'store'] );
Route::post('/save-collective', [CollectiveController::class, 'store'] );
Route::put('/update-collective/{collective}', [CollectiveController::class, 'update']);

// Collectives Routes
Route::resource('/collectif', 'CollectiveController');
Route::post('/home-collectives', [CollectiveController::class, 'homeColl']);
Route::get('/all-collectif', [CollectiveController::class, 'indexForAdmin'])->name('all_collectives');
Route::post('/collective/add-picture', [CollectiveController::class, 'addPicture']);
Route::delete('/delete-collective/{collective}', [CollectiveController::class, 'destroy']);
Route::delete('/delete-collective-picture/{collective}', [CollectiveController::class, 'deleteImg']);

// Pages Route
Route::get('/page/{staticPage}', [StaticPageController::class, 'showForAll']);
Route::get('/contact', [ContactController::class, 'show'])->name('page_contact');
Route::post('contact/envoyer', [ContactController::class, 'store'])->name('store_contact');

Route::post('/admin/profile-name/{user}', [UserController::class, 'showName']);
Route::post('/filtered-initiatives', [InitiativeController::class, 'filterInit']);

Route::post('/like/idea/{int}', [ReactionController::class, 'likeIdeas']);
Route::post('/like/initiative/{int}', [ReactionController::class, 'likeInitiative']);

// Pages Moderate
Route::get('/admin/moderate', [ModerateController::class, 'index'])->name('moderate.index');
Route::put('/admin/moderate/reject/{moderate}', [ModerateController::class, 'reject'])->name('moderate.reject');
Route::put('/admin/moderate/validate/{moderate}', [ModerateController::class, 'valide'])->name('moderate.validate');
Route::post('/moderate', [ModerateController::class, 'signal']);


// Photos route
Route::post('/save-init-photo', [PhotoController::class, 'storeForInit'])->name('save-init-photo');

app/Models/Collective.php
<?php

namespace App\Models;
use App\Models\Category;
use App\Models\Initiative;
use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Collective extends Model
{

  protected $guarded = [];

  protected $hidden = [
      'created_at', 'updated_at',
  ];

  public function initiatives(): HasMany
  {
    return $this->hasMany(Initiative::class);
  }

  public function initiativesCount()
  {
    return $this->initiatives()->count();
  }

  public function owner(): HasOne
  {
    return $this->hasOne(User::class, 'id', 'user_id');
  }

  public function members(): BelongsToMany
  {
    return $this->belongsToMany(User::class)->withPivot('banned')->withTimestamps();
  }
}

app/Http/Controllers/CollectiveController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Models\Collective;
use App\Models\Initiative;
use Illuminate\Http\Request;


class CollectiveController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $collectives = Collective::orderBy('name', 'desc')->get();

      return view('collectives.index', compact('collectives'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //$this->authorize('create', Category::class);
        $owner = $request->user()->id;

        //dd($request);
        $collective = Collective::create($this->validateRequest($request, $owner));

        //$this->storeImage($collective);
        $collective->save();

        if ($request->expectsJson()) {
            return response()->json([
              'status' => 'OK',
              'type' => 'collective',
              'data' => $collective
            ]);
        }

        //return redirect()->route('categories.index')->with('message', 'Catégorie créée');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Collective $collectif)
    {
        $collectif->load('initiatives');
        foreach ($collectif->initiatives as $initiative) {
          $initiative->load('category');
        }

        $ajax = $request->expectsJson();

        if ($ajax) {
            return response()->json([
              'status' => 'OK',
              'type' => 'collectif',
              'data' => Collective::find($request->id)
            ]);
        }

        return view('collectives.show', compact('collectif'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  App\Models\Collective $collective
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Collective $collective)
    {

      $owner = $request->user()->id;
      $collective->update($this->validateRequest($request, $owner));
      $collective->save();

      $ajax = $request->expectsJson();

      if ($ajax) {
          return response()->json([
            'status' => 'OK',
            'type' => 'collectif',
            'data' => $collective
          ]);
      }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Collective $collective)
    {

        $collective->delete();
    }

    private function validateRequest($request, $owner)
    {
        $request['user_id'] = $owner;

        return request()->validate([
            'name' => 'required|string|min:3',
            'url' => 'nullable|url',
            'address1' => 'nullable|string|min:3',
            'address2' => 'nullable|string|min:3',
            'zip_code' => 'nullable|string|min:3',
            'city' => 'nullable|string|min:3',
            'user_id' => 'integer',
            'description' => 'nullable|string|min:3',
            'values' => 'nullable|string|min:3',
            'testimony' => 'nullable|string|min:3',
            'home' => 'nullable|integer'
        ]);
    }

    public function addPicture(Request $request)
    {
        $data = request()->validate([
            'id' => 'required|integer',
            'picture' => 'sometimes|file|image|max:5000',
        ]);

        $collective = Collective::find($data['id']);

        $this->storeImage($collective);

        if ($request->expectsJson()) {
            return response()->json([
              'status' => 'OK',
              'type' => 'collective',
              'data' => $collective
            ]);
        }
    }

    private function storeImage($collective)
    {
        if(request()->has('picture')){
            $collective->update([
                'picture'=> request()->picture->store('uploads/collective', 'public'),
            ]);
        }
    }

    public function showAdmin(Request $request)
    {
      return view('admin.collectives.admin');
    }

    public function refColl(Request $request)
    {
      $user = $request->user()->id;
      $collectives = Collective::where('user_id', '=', $user)->orderBy('created_at', 'desc')->get()->load('initiatives');

      return view('admin.collectives.ref-coll', compact('collectives'));
    }

    public function memberColl(Request $request)
    {
        $collectives = User::find($request->user()->id)->load('participants')->participants;
        //dd($collectives);
      //$collectives = User::find($request->user()->id)->collectives;

      return view('admin.collectives.member-coll', compact('collectives'));
    }

    public function deleteImg(Request $request, Collective $collective)
    {
      $collective->picture = NULL;
      $collective->save();
    }

    public function createColl(Request $request)
    {
      $user = $request->user()->id;
      // $collectives = Collective::where('user_id', '=', $user)->get();
      return view('admin.collectives.create');
    }

    public function indexForAdmin()
    {
      $collectives = Collective::withCount('initiatives', 'members')->orderBy('name', 'desc')->get();

      return view('admin.collectives.index', compact('collectives'));
    }

    public function homeColl(Request $request) {

      $collectives = Collective::where('home', '1')->limit(3)->get();

      if($request->expectsJson()) {
        return response()->json([
          'status' => 'OK',
          'type' => 'collective',
          'data' => $collectives
          ]
        );
      }
    }
}

resources/views/admin/collectives/admin.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.menu')

<div class="content_container">
<h1 class="section_title">Gérer vos collectifs</h1>
  <div class="collectives_links">
    <a class="btn" href="{{route('collectives.ref-coll')}}">Voir les collectifs dont vous êtes référent</a>
    <a  class="btn" href="{{route('collectives.member-coll')}}">Voir les collectifs dont vous êtes membre</a>
    <a  class="btn" href="{{route('collectives.create')}}">Créer un nouveau collectif</a>
    @can('create', App\Models\FicConfig::class)
      <a class="btn" href="{{route('all_collectives')}}">Voir tous les collectifs</a>
    @endcan
  </div>
</div>

@endsection

resources/views/admin/collectives/create.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.menu')
<div class="content_container">
  <div id="createColl">
    <h1 class="section_title">Créer un nouveau collectif</h1>
    <addcollective :admin="{{true}}"/>
  </div>
  <div class="return">
  <a class="btn" href="{{route('collectives.admin')}}">Retour</a>
</div>
</div>
@endsection

resources/views/admin/collectives/index.blade.php
@extends('layouts.app')

@section('content')
<div id="collList">
	<h1 class="section_title">Liste de tous les collectifs</h1>

	<div class="coll_list">
	@foreach ($collectives as $collective)
	<div>
	    <a href="collectif/{{$collective->id}}" title="Voir le détail du collectif"><h2>{{$collective->name}}</h2></a>
	    <p>{{$collective->description}}</p>
	    <div>Initiatives : {{$collective->initiatives_count}}</div>
	    <div>Membres : {{$collective->members_count + 1 }}</div>
	    <div>
	      <checkbox :collective="{{json_encode($collective)}}"/>
	    </div>
    </div>
	@endforeach
	</div>
</div>
@endsection

resources/views/admin/collectives/member-coll.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.menu')
@php
if (Auth::user()) {
  $user = Auth::user();
} else {
  $user = Null;
}
@endphp
<div class="content_container">
  <div id="collAdmin">
    <h1 class="section_title">Les collectifs dont vous êtes membre</h1>
    @foreach ($collectives as $collective)
    <div>
    <collective :collectives="{{json_encode($collectives)}}" :collective="{{json_encode($collective)}}" :admin="{{true}}"/>
    </div>
    <div id="collective_members">
      <Members :id="{{ $collective->id }}" :type="'collective'" :members="{{ json_encode($collective->members) }}" :user="{{ json_encode($user) }}" :orga="{{ json_encode($collective->owner) }}" />
    </div>
    @endforeach
  </div>
  <div class="return">
    <a class="btn" href="{{route('collectives.admin')}}">Retour</a>
  </div>
</div>
@endsection

resources/views/admin/collectives/ref-coll.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.menu')

@php
if (Auth::user()) {
  $user = Auth::user();
} else {
  $user = Null;
}
@endphp

<div class="content_container">
  <div id="collAdmin">
    <h1 class="section_title">Les collectifs dont vous êtes référent</h1>
    @foreach ($collectives as $collective)
    <div>
    <collective :collectives="{{json_encode($collectives)}}" :collective="{{json_encode($collective)}}" :admin="{{true}}"/>
    </div>
    <div id="collective_members">
      <Members :id="{{ $collective->id }}" :type="'collective'" :members="{{ json_encode($collective->members) }}" :user="{{ json_encode($user) }}" :orga="{{ json_encode($user) }}" />
    </div>
    @endforeach
  </div>
  <div class="return">
    <a class="btn" href="{{route('collectives.admin')}}">Retour</a>
  </div>
</div>
@endsection